-- Stage 4: 초기 스키마
-- 지금까지 ddl-auto(update)가 만들던 테이블들을 Flyway 관리로 이관.
-- 이후로는 스키마 변경을 V2, V3... 마이그레이션으로 버전 관리한다.

-- ─── 유저 ───────────────────────────────────────────────
CREATE TABLE users (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          varchar(255) NOT NULL,
    password       varchar(255),
    nickname       varchar(255) NOT NULL,
    role           varchar(255) NOT NULL,
    email_verified boolean      NOT NULL,
    provider       varchar(255) NOT NULL,
    provider_id    varchar(255),
    created_at     timestamp(6) NOT NULL,
    updated_at     timestamp(6) NOT NULL,
    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT uq_users_nickname UNIQUE (nickname),
    CONSTRAINT uq_users_provider UNIQUE (provider, provider_id),
    CONSTRAINT ck_users_role     CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_provider CHECK (provider IN ('LOCAL', 'GOOGLE', 'NAVER'))
);

-- ─── 이메일 인증 토큰 ────────────────────────────────────
CREATE TABLE email_verification_token (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      varchar(255) NOT NULL,
    user_id    bigint       NOT NULL,
    expires_at timestamp(6) NOT NULL,
    used_at    timestamp(6),
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uq_evt_token UNIQUE (token)
);

-- ─── 알고리즘 태그 ───────────────────────────────────────
CREATE TABLE algorithm_tags (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    CONSTRAINT uq_algorithm_tags_name UNIQUE (name)
);

-- ─── 문제 ───────────────────────────────────────────────
CREATE TABLE problems (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           varchar(255) NOT NULL,
    source          varchar(255) NOT NULL,
    level           integer      NOT NULL,
    acceptance_rate double precision,
    adjusted_level  double precision,
    tier            varchar(255),
    link            varchar(255) NOT NULL,
    created_at      timestamp(6) NOT NULL,
    updated_at      timestamp(6) NOT NULL,
    CONSTRAINT ck_problems_source CHECK (source IN (
        'PRACTICE', 'KAKAO_BLIND', 'KAKAO_INTERNSHIP', 'KAKAO_CODE',
        'MONTHLY_CHALLENGE', 'WEEKLY_CHALLENGE', 'SUMMER_WINTER',
        'PCCE', 'PCCP', 'SQL', 'OTHER')),
    CONSTRAINT ck_problems_tier CHECK (tier IN (
        'BRONZE_III', 'BRONZE_II', 'BRONZE_I',
        'SILVER_III', 'SILVER_II', 'SILVER_I',
        'GOLD_III', 'GOLD_II', 'GOLD_I',
        'PLATINUM_III', 'PLATINUM_II', 'PLATINUM_I',
        'DIAMOND_III', 'DIAMOND_II', 'DIAMOND_I'))
);

-- ─── 문제-태그 연결 (대리키 + (problem_id, tag_id) 유니크) ──
CREATE TABLE problem_tags (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL,
    tag_id     bigint NOT NULL,
    CONSTRAINT uq_problem_tags UNIQUE (problem_id, tag_id),
    CONSTRAINT fk_problem_tags_problem FOREIGN KEY (problem_id) REFERENCES problems(id),
    CONSTRAINT fk_problem_tags_tag     FOREIGN KEY (tag_id)     REFERENCES algorithm_tags(id)
);
