-- Stage 5: 풀이(Solution) + 메모(Memo)

-- ─── 풀이 ───────────────────────────────────────────────
-- (user_id, problem_id) 유니크 = "한 유저 한 문제 풀이 1개" (upsert의 기준)
-- user_id FK는 ON DELETE CASCADE → 유저 탈퇴 시 풀이 자동 정리
CREATE TABLE solutions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    problem_id bigint       NOT NULL,
    code       text         NOT NULL,
    language   varchar(255) NOT NULL,
    starred    boolean      NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uq_solutions_user_problem UNIQUE (user_id, problem_id),
    CONSTRAINT fk_solutions_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
    CONSTRAINT fk_solutions_problem FOREIGN KEY (problem_id) REFERENCES problems(id)
);

-- ─── 메모 (풀이별 1:1) ──────────────────────────────────
-- solution_id 유니크 = 진짜 1:1 보장. 풀이 삭제 시 메모도 CASCADE 정리
CREATE TABLE memos (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solution_id   bigint NOT NULL,
    wrong_reason  text,
    logic         text,
    key_functions text,
    free_note     text,
    CONSTRAINT uq_memos_solution UNIQUE (solution_id),
    CONSTRAINT fk_memos_solution FOREIGN KEY (solution_id) REFERENCES solutions(id) ON DELETE CASCADE
);
