-- Stage 6: 난이도 피드백(LevelFeedback) → 티어 자동 계산의 입력 데이터

-- (user_id, problem_id) 유니크 = "한 유저 한 문제 피드백 1개" (upsert 기준)
-- 두 FK 모두 ON DELETE CASCADE → 유저 탈퇴/문제 삭제 시 피드백 자동 정리
CREATE TABLE level_feedback (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    problem_id bigint       NOT NULL,
    level      integer      NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uq_level_feedback_user_problem UNIQUE (user_id, problem_id),
    CONSTRAINT fk_level_feedback_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
    CONSTRAINT fk_level_feedback_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);
