-- Stage 7: 학습 노트(Note) + 자유 태그(note_tags)

-- 문제와 무관한 유저 소유 노트. user_id FK ON DELETE CASCADE → 탈퇴 시 자동 정리
CREATE TABLE notes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    type       varchar(255) NOT NULL,
    title      varchar(255) NOT NULL,
    body       text         NOT NULL,
    language   varchar(255),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT chk_notes_type CHECK (type IN ('CODE', 'PATTERN', 'MISTAKE', 'OTHER')),
    CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- @ElementCollection 매핑 테이블: (note_id, tag). 노트 삭제 시 CASCADE 정리
CREATE TABLE note_tags (
    note_id bigint       NOT NULL,
    tag     varchar(255) NOT NULL,
    CONSTRAINT fk_note_tags_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE
);
CREATE INDEX idx_note_tags_note ON note_tags(note_id);
