-- Stage 8 (Phase 1): 커뮤니티 게시글 + 댓글

-- 작성자 탈퇴 시 user_id → SET NULL (글은 보존, 표시만 익명화). 문제 삭제 시 problem_id → SET NULL.
CREATE TABLE community_posts (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint,
    problem_id     bigint,
    type           varchar(255) NOT NULL,
    title          varchar(255) NOT NULL,
    content        text         NOT NULL,
    is_private     boolean      NOT NULL,
    hidden         boolean      NOT NULL,
    status         varchar(255),
    admin_reply    text,
    admin_reply_at timestamp(6),
    created_at     timestamp(6) NOT NULL,
    updated_at     timestamp(6) NOT NULL,
    CONSTRAINT chk_post_type CHECK (type IN ('QUESTION', 'SOLUTION_SHARE', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST')),
    CONSTRAINT chk_post_status CHECK (status IS NULL OR status IN ('IN_PROGRESS', 'RESOLVED')),
    CONSTRAINT fk_posts_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE SET NULL,
    CONSTRAINT fk_posts_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE SET NULL
);
CREATE INDEX idx_posts_created ON community_posts(created_at);
CREATE INDEX idx_posts_type ON community_posts(type);

-- 글 삭제 시 댓글 CASCADE 정리. 작성자 탈퇴 시 user_id → SET NULL (댓글 보존).
CREATE TABLE comments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint       NOT NULL,
    user_id    bigint,
    content    text         NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES community_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)           ON DELETE SET NULL
);
CREATE INDEX idx_comments_post ON comments(post_id);
