-- Stage 8 (Phase 2): 커뮤니티 게시글 추천/비추천

-- (user_id, post_id) 유니크 = 1인 1표 (upsert 기준). 투표는 보존 대상 아님 → 둘 다 CASCADE.
CREATE TABLE post_votes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    post_id    bigint       NOT NULL,
    value      integer      NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT chk_vote_value CHECK (value IN (1, -1)),
    CONSTRAINT uq_post_votes_user_post UNIQUE (user_id, post_id),
    CONSTRAINT fk_post_votes_user FOREIGN KEY (user_id) REFERENCES users(id)           ON DELETE CASCADE,
    CONSTRAINT fk_post_votes_post FOREIGN KEY (post_id) REFERENCES community_posts(id) ON DELETE CASCADE
);
CREATE INDEX idx_post_votes_post ON post_votes(post_id);
