-- Stage 9: 알림(Notification). payload 는 종류별로 구조가 달라 jsonb 한 컬럼에 저장.

CREATE TABLE notifications (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    type       varchar(255) NOT NULL,
    payload    jsonb,
    is_read    boolean      NOT NULL,
    read_at    timestamp(6),
    created_at timestamp(6) NOT NULL,
    CONSTRAINT chk_notif_type CHECK (type IN (
        'COMMENT', 'ADMIN_REPLY', 'STATUS_CHANGE', 'POST_HIDDEN',
        'REPORT_RESOLVED', 'NEW_REPORT', 'TIER_UP', 'STALE_SUGGESTION')),
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 목록은 (user_id 필터 + id 내림차순), 카운트/미읽음 목록은 미읽음만
CREATE INDEX idx_notif_user_id ON notifications(user_id, id DESC);
CREATE INDEX idx_notif_user_unread ON notifications(user_id) WHERE is_read = false;
