-- Stage 8 (Phase 3): 게시글 신고

-- (user_id, post_id) 유니크 = 중복 신고 방지. 유저/글 삭제 시 신고도 CASCADE 정리.
CREATE TABLE post_reports (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL,
    post_id    bigint       NOT NULL,
    reason     varchar(255) NOT NULL,
    status     varchar(255) NOT NULL,
    admin_note varchar(255),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT chk_report_status CHECK (status IN ('OPEN', 'HANDLED', 'DISMISSED')),
    CONSTRAINT uq_post_reports_user_post UNIQUE (user_id, post_id),
    CONSTRAINT fk_post_reports_user FOREIGN KEY (user_id) REFERENCES users(id)           ON DELETE CASCADE,
    CONSTRAINT fk_post_reports_post FOREIGN KEY (post_id) REFERENCES community_posts(id) ON DELETE CASCADE
);
CREATE INDEX idx_post_reports_post ON post_reports(post_id);
CREATE INDEX idx_post_reports_status ON post_reports(status);
